### PR TITLE
updated SSSC co-chair

### PR DESCRIPTION
**Pull request by mschwamb**
updated info for SSSC co-chair as suggested by @rhiannonlynne  Also if possible could I be added to the github organization

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
I'm going to approve the PR, because I'm not co-chair anymore :)

**Comment by rhiannonlynne** [comment]
Meg, you should also have an invitation to join the github organization.

**Comment by mschwamb** [comment]
Thanks @rhiannonlynne . Can you also add me as an owner to the repo. Currently it says I'm a member. I think owner has some more privileges

**Comment by rhiannonlynne** [comment]
Done.

**Comment by mschwamb** [comment]
Thanks 💯

**Pull request merged**
